### PR TITLE
Renamed getDate to getDay. Fixes #2

### LINKED ISSUE #2: getDate
Hi, its small yet annoying issue - "getDate" should actually be "getDay" as it returns only a day of the month.

### PR DESCRIPTION
**Pull request by sudar**
Would appreciate a merge.

### CODE REVIEW

**Comment by hurik** [comment]
Hi Sudar,

I merged your pull request. I also changed the setDate() Method to setDay() and updated keywords.txt and the example.

It would be nice if someone can test it. The highlighting in Arduino Software and the example, if it still working without problems.

Bye,
Andreas

**Comment by davidhbrown** [comment]
Andreas and Sudar, thanks so much for doing this. I haven't had an opportunity to work on an Arduino for a quite while and don't even have the environment set up on my current computer :-( 

I am concerned, though, that this change will break existing code that uses the getDate() function to retrieve the day-of-the-month value. 

I would suggest two mutually compatible solutions. One would be to relabel the release 1.0 and just document the change carefully for users of the older version of the library. Another approach would be to create a stub function getDate() that simply returns getDay(). The getDate() method would be marked as deprecated (I don't think the Arduino IDE has support for annotations, but a comment would do). This second option would of course slightly bloat the code.

Any thoughts?

**Comment by hurik** [comment]
Hi David,

after I commited the changes I had the same thoughts, that it is not the best idea to change the api ...
And by the way: I didn't ask you first because I wasn't sure if you still looking over the repo ... sorry for that ...

I could revert the changes, and could add the day setter and getter like this:

``` c
int RealTimeClockDS1307::getDay()
{
  return getDate();
}
void RealTimeClockDS1307::setDay(int d)
{
  setDate(d);
}
```

This wouldn't bloat the code to much ...

Also we could make a branch, but this wouldn't be to easy for new users ...

It's your repo and your decision ...

Bye,
Andreas

**Comment by sudar** [comment]
@davidhbrown @hurik 

Even I think adding the compatibility function suggested by @hurik is the right solution.

I can send a new pull request if needed.

**Comment by hurik** [comment]
I made the changes.

Sudar can you check if it is working?

**Comment by sudar** [comment]
@hurik I just checked it in the Arduino IDE and everything seems to be working fine.

Thanks merging the code.

**Pull request merged**
